id: I18364385
source: https://sakyaresearch.org
source_file: null
initial_creation_type: input
imported: '2022-06-18T22:24:47.690676'
last_modified: '2022-06-18T22:24:47.690743'
parser: null
source_metadata:
  title: sGra tshad pa Rin chen rnam rgyals (1318–1388) Sakya Genealogy
  author: sgra tshad pa rin chen rnam rgyal/
  description: 'Digital version 1.0 {Wylie}; WYLIE COPY of master xml (completed:
    2018-09-06); revision in process, thematic TEI markup'
  file_info:
  - 'Language: Wylie'
  - 'Coverage: Full Text'
  - 'Accessible: publicly'
  responibilities:
  - Digital edition:Sakya Research Centre (src)
  - Text input:Lobsang Gyaltsen, Dharamsala (lg)
  - Editorial process:Mathias Fermer (mf)
  - TEI Encoding:Sakya Research Centre
  - TEI Markup:Mathias Fermer (mf)
  - Revisions/Corrections:-
  text_witnesses: https://sakyaresearch.org/sources/2435
  bases:
    9e2e:
      title: sGra tshad pa Rin chen rnam rgyals (1318–1388) Sakya Genealogy
      order: 1
      base_file: 9e2e.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
